version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:root
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME:root   
      - ME_CONFIG_BASICAUTH_PASSWORD:root
      - ME_CONFIG_MONGODB_ENABLE_ADMIN:true
    ports:
      - 8081:8081
    
networks:
  default:
    name: mongodb_network