version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2022
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: always
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2022
       ME_CONFIG_MONGODB_PORT: 27017
       ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    ports:
      - 8081:8081
    links:
      - mongo
    networks:
      - mongo-network  

networks: 
    mongo-network:
      driver: bridge
